#!/bin/bash

CWD=$(dirname $0)
API="$1"
CLUSTER_CA_FILE="$2"
CLIENT_CERT_FILE="$3"
CLIENT_KEY=$(cat $HOME/.kube/$USER.key | base64 | tr -d "\n")

if [[ $# -ne 3 ]]
then
    cat <<EOF
    Usage: $0 <API_URL> <CA_CERT_FILE> <USER_CERT_FILE>"
        API_URL: The URL to the kube-apiserver.
            Ex: https://kube-apiserver:6443
        CA_CERT_FILE: The kube-apiserver CA certificate
            It should be provided by your admin
        USER_CERT_FILE: Your signed certificate
            It should be provided by your admin
EOF
    exit 0
fi

if [[ ! -e "$CLUSTER_CA_FILE" ]]
then
    echo "Cluster CA certificate not found."
    exit 0
fi

if [[ ! -e "$CLIENT_CERT_FILE" ]]
then
    echo "Cluster CA certificate not found."
    exit 0
fi

if [[ "x$CLIENT_KEY" == "x" ]]
then
    echo "Invalid certificate path, please set USER variable so that $HOME/.kube/\$USER.key points to your key"
    echo "Current USER=$USER"
    exit 1
fi

cp "$CLUSTER_CA_FILE" "$HOME/.kube/ca.crt"
cp "$USER_CERT_FILE" "$HOME/.kube/$USER.crt"
CLUSTER_CA=$(cat "$CLUSTER_CA_FILE" | base64 | tr -d "\n")
CLIENT_CERT=$(cat "$CLIENT_CERT_FILE" | base64 | tr -d "\n")

KUBECFG_TEMP=$(mktemp)

sed "s/---CLUSTER-CA---/$CLUSTER_CA/g;s/---API-URL---/$API_URL/g;s/---CLIENT-CERT---/$CLIENT_CERT/g;s/---CLIENT-KEY---/$CLIENT_KEY/g" "$CWD/template/kubeconfig" >"$KUBECFG_TEMP"

echo -e "Please try to write the following content in $HOME/.kube/config\n"

cat "$KUBECFG_TEMP"

